blog/urls.py
from django.urls import path

from . import views

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog'),
    path('<int:post_id>/', views.post, name='post'),
]

home/urls.py
from django.urls import path

from . import views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),  
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404

from . import data

def index(request):
    context = {
        'title': 'Blog Page',
        'posts': data.posts
    }

    return render(
        request, 
        'blog/index.html', 
        context    
    )


def post(request: HttpResponse, post_id:int):
    
    found_post = None

    for post in data.posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404('Post not found')
    
    context = {
        'title': 'Blog Page',
        'post': found_post
    }

    return render(
        request, 
        'blog/post.html', 
        context    
    )

home/views.py
from django.shortcuts import render

def index(request):

    context = {
        'title': 'Home Page',
        'content': 'This is the home page content'
    }

    return render(
        request, 
        'home/index.html', 
        context    
    )

blog/templates/blog/index.html
{% extends "global/base.html" %}

{% block title %} BLOG {% endblock title %}


{% block posts %}
    {% for post in posts %}
        {% include "global/partials/postblock.html" %}
    {% endfor %}
{% endblock posts %}

blog/templates/blog/post.html
{% extends "global/base.html" %}

{% block title %} BLOG {% endblock title %}


{% block posts %}
    <article class="post single-post">
        <header>
            <h2 class="post__title">
                <a href="{% url "blog:post" post.id%}">{{ post.title }}</a>
            </h2>
        </header>
        <div class="post__body">
            {{ post.body }}
        </div>
    </article>
{% endblock posts %}

home/templates/home/index.html
{% extends "global/base.html" %}

{% block title %} 
    {{ title}}
{% endblock title %}


{% block home %}
    <h1>Home</h1>
{% endblock home %}